# Generated by Django 4.1.7 on 2023-03-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_user_responses_responder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='participants',
            new_name='participant',
        ),
    ]
