# Generated by Django 4.1.7 on 2023-03-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='Caption',
            new_name='caption',
        ),
    ]
