# Generated by Django 4.1.7 on 2023-03-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_remove_feed_shares_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
