# Generated by Django 4.1.7 on 2023-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_pic_alter_academicsinfo_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_cover',
            field=models.ImageField(blank=True, default='=profile-cover/default-profile-cover.jpg', null=True, upload_to='profile-cover'),
        ),
    ]
